### ISSUE TITLE
meant to be a public repo?

### ISSUE THREAD

**Issue by david-wolgemuth** [SpotOnInc/helmcharts#74]
was surprised to see this as a public repo - not sure if it matters, but wanted to ask

i see this in the readme description:

> Spoton internal Helm charts repository.

@asiegman @fcooper-spoton

**Comment by fcooper-spoton** [comment]
Helm charts are by design public things. This is mostly an accident of language.  The chart isn't useful to anyone outside of SpotOn, not even a little bit.

Feel free to make a PR.
